# Generated by Django 5.2 on 2026-04-22 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('pix', 'PIX'), ('credito', 'Crédito'), ('debito', 'Débito'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('dinheiro', 'Dinheiro'), ('cheque', 'Cheque'), ('outro', 'Outro')], default='boleto', max_length=15)),
                ('quantidade_parcelas', models.IntegerField(blank=True, choices=[(1, '1 parcela'), (2, '2 parcelas'), (3, '3 parcelas'), (4, '4 parcelas'), (5, '5 parcelas'), (6, '6 parcelas'), (7, '7 parcelas'), (8, '8 parcelas'), (9, '9 parcelas'), (10, '10 parcelas'), (11, '11 parcelas'), (12, '12 parcelas')], null=True)),
                ('cobranca_imediata', models.BooleanField(default=False)),
                ('nome_contato_envio_nf', models.CharField(default='', max_length=50)),
                ('contato_envio_nf', models.EmailField(default='', max_length=254)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('faturada', models.BooleanField(default=False)),
                ('numero_nf', models.IntegerField(blank=True, null=True)),
                ('data_faturamento', models.DateField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
