from .Profile import Profile
from .Contato import Contato
from .Cliente import Cliente
from .RepositorioMiniOS import RepositorioMiniOS
from .MiniOS import MiniOS
from .Repositorio import Repositorio
from .Servico import Servico
from .Tarefa import Tarefa
from .OrdemServico import OrdemServico