# Generated by Django 5.2 on 2026-04-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_inscricao', models.CharField(blank=True, choices=[('cnpj', 'CNPJ'), ('cpf', 'CPF'), ('cei', 'CEI'), ('cno', 'CNO'), ('caepf', 'CAEPF')], default='cnpj', max_length=10, null=True)),
                ('numero_inscricao', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_cliente', models.CharField(blank=True, choices=[('gestao', 'Gestão'), ('avulso', 'Avulso'), ('fornecedor', 'Fornecedor')], default='gestao', max_length=10, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('nome_representante', models.CharField(blank=True, max_length=50, null=True)),
                ('setor_representante', models.CharField(blank=True, max_length=50, null=True)),
                ('email_representante', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato_representante', models.CharField(blank=True, max_length=50, null=True)),
                ('cobranca_revisao_alteracao', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
