# Generated by Django 4.2.25 on 2026-07-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='complexidade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], null=True),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='horas_estimadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='catalogooperacional',
            name='complexidade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], null=True),
        ),
        migrations.AddField(
            model_name='catalogooperacional',
            name='horas_estimadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
