# Generated by Django 4.2.25 on 2026-07-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservicooperacional',
            name='complexidade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], null=True),
        ),
        migrations.AddField(
            model_name='ordemservicooperacional',
            name='horas_estimadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ordemservicooperacional',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservicooperacional',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='baixa', max_length=10),
        ),
        migrations.AddField(
            model_name='servico',
            name='complexidade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='horas_estimadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='baixa', max_length=10),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='baixa', max_length=10),
        ),
    ]
