# Generated by Django 4.2.25 on 2026-07-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0002_ordemservico_prazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='horas_estimadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
