# Generated by Django 5.2 on 2026-04-22 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_inscricao', models.CharField(blank=True, choices=[('cnpj', 'CNPJ'), ('cpf', 'CPF'), ('cei', 'CEI'), ('cno', 'CNO'), ('caepf', 'CAEPF')], default='cnpj', max_length=10, null=True)),
                ('numero_inscricao', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_cliente', models.CharField(blank=True, choices=[('gestao', 'Gestão'), ('avulso', 'Avulso'), ('fornecedor', 'Fornecedor')], default='gestao', max_length=10, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nome_representante', models.CharField(blank=True, max_length=50, null=True)),
                ('setor_representante', models.CharField(blank=True, max_length=50, null=True)),
                ('email_representante', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato_representante', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_ativo', models.CharField(blank=True, choices=[('sim', 'SIM'), ('nao', 'NÃO')], default='sim', max_length=5, null=True)),
                ('cobranca_revisao_alteracao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepositorioMiniOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('valor', models.FloatField(blank=True, default='0.0', null=True)),
                ('forma_pagamento', models.CharField(choices=[('pix', 'PIX'), ('credito', 'Crédito'), ('debto', 'Débto'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('dinheiro', 'Dinheiro'), ('check', 'Check'), ('outro', 'Outro')], default='boleto', max_length=30)),
                ('quantidade_parcelas', models.IntegerField(blank=True, choices=[(1, '1 parcela'), (2, '2 parcelas'), (3, '3 parcelas'), (4, '4 parcelas'), (5, '5 parcelas'), (6, '6 parcelas'), (7, '7 parcelas'), (8, '8 parcelas'), (9, '9 parcelas'), (10, '10 parcelas'), (11, '11 parcelas'), (12, '12 parcelas')], null=True)),
                ('cobranca_imediata', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=5)),
                ('faturamento_1', models.DateField(blank=True, null=True)),
                ('nome_contato_envio_nf', models.CharField(default=' ', max_length=50)),
                ('contato_envio_nf', models.EmailField(default=' ', max_length=254)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('concluida', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=5, null=True)),
                ('faturamento', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=5, null=True)),
                ('numero_nf', models.IntegerField(blank=True, null=True)),
                ('data_faturamento', models.DateField(blank=True, null=True)),
                ('usuario_criador', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='ordemServico.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Diretor'), (2, 'Administrativo'), (3, 'Líder Técnico'), (4, 'Sub-Líder Técnico'), (5, 'Técnico'), (6, 'Gestor Comercial')], default=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiniOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, default=1, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('nao_iniciado', 'NÃO INICIADO'), ('em_andamento', 'EM ANDAMENTO'), ('finalizada', 'FINALIZADA')], default='nao_iniciado', max_length=15, null=True)),
                ('revisao_cliente', models.BooleanField(blank=True, default=False, null=True)),
                ('faturamento', models.CharField(blank=True, choices=[('sim', 'SIM'), ('nao', 'NÃO')], default='nao', max_length=3, null=True)),
                ('n_nf', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_minios', to='ordemServico.cliente')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_minios', to='ordemServico.profile')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servico_minios', to='ordemServico.repositoriominios')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('em_espera', 'EM ESPERA'), ('em_andamento', 'EM ANDAMENTO'), ('concluida', 'CONCLUÍDA')], default='em_espera', max_length=15, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='ordemServico.ordemservico')),
                ('repositorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordemServico.repositorio')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('nao_iniciada', 'NÃO INICIADA'), ('em_andamento', 'EM ANDAMENTO'), ('concluida', 'CONCLUÍDA')], default='nao_iniciada', max_length=15, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordemServico.ordemservico')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_profile', to='ordemServico.profile')),
                ('servico', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='ordemServico.servico')),
            ],
        ),
    ]
