# Generated by Django 4.0.6 on 2024-09-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data_criacao',
            field=models.DateField(),
        ),
    ]
