# Generated by Django 5.1.1 on 2024-09-30 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0003_alter_tarefa_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minios',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_minios', to='ordemServico.cliente'),
        ),
        migrations.AlterField(
            model_name='minios',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_minios', to='ordemServico.profile'),
        ),
        migrations.AlterField(
            model_name='minios',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servico_minios', to='ordemServico.repositoriominios'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='ordemServico.cliente'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='ordemServico.ordemservico'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_profile', to='ordemServico.profile'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='servico',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='ordemServico.servico'),
        ),
    ]
