# Generated by Django 5.1.1 on 2024-11-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0004_alter_minios_cliente_alter_minios_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cobranca_revisao_alteracao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='renovacao_automativa',
            field=models.BooleanField(default=False),
        ),
    ]
