# Generated by Django 5.1.1 on 2024-11-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0005_cliente_cobranca_revisao_alteracao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='renovacao_automativa',
            new_name='renovacao_automatica',
        ),
    ]
