# Generated by Django 5.1.1 on 2024-11-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0006_rename_renovacao_automativa_cliente_renovacao_automatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='minios',
            name='faturamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='minios',
            name='n_nf',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
