# Generated by Django 5.1.1 on 2024-11-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0007_minios_faturamento_minios_n_nf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minios',
            name='faturamento',
            field=models.BooleanField(default=True),
        ),
    ]
