# Generated by Django 5.1.1 on 2024-11-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0008_alter_minios_faturamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cobranca_revisao_alteracao',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='minios',
            name='faturamento',
            field=models.BooleanField(default=False),
        ),
    ]
