# Generated by Django 5.1.1 on 2024-11-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0009_alter_cliente_cobranca_revisao_alteracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cobranca_revisao_alteracao',
        ),
    ]
