# Generated by Django 5.1.1 on 2024-11-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0010_remove_cliente_cobranca_revisao_alteracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cobranca_revisao_alteracao',
            field=models.BooleanField(default=True),
        ),
    ]
