# Generated by Django 5.1.1 on 2024-11-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0011_cliente_cobranca_revisao_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minios',
            name='faturamento',
            field=models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO')], default='', max_length=3),
        ),
    ]
