# Generated by Django 5.1.1 on 2024-11-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0012_alter_minios_faturamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
