# Generated by Django 5.1.1 on 2024-12-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0013_tarefa_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minios',
            name='faturamento',
            field=models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(blank=True, choices=[('nao_iniciada', 'NÃO INICIADA'), ('em_andamento', 'EM ANDAMENTO'), ('concluida', 'CONCLUÍDA')], default='nao_iniciada', max_length=15, null=True),
        ),
    ]
