# Generated by Django 5.1.1 on 2024-12-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0014_alter_minios_faturamento_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minios',
            name='faturamento',
            field=models.CharField(blank=True, choices=[('sim', 'SIM'), ('nao', 'NÃO')], default='nao', max_length=3, null=True),
        ),
    ]
