# Generated by Django 5.2 on 2025-04-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0014_alter_tarefa_status'),
        ('ordemServico', '0015_alter_minios_faturamento'),
    ]

    operations = [
    ]
