# Generated by Django 5.2 on 2026-01-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0020_remove_cliente_renovacao_automatica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Diretor'), (2, 'Administrativo'), (3, 'Líder Técnico'), (4, 'Sub-Líder Técnico'), (5, 'Técnico'), (6, 'Gestor Comercial')], default=5),
        ),
    ]
