# Generated by Django 5.2 on 2026-02-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0021_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='minios',
            name='revisao_cliente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
