from .OrdemServicoViewSet import OrdemServicoViewSet
from .ProfileViewSet import ProfileViewSet
from .ClienteViewSet import ClienteViewSet
from .RepositorioViewSet import RepositorioViewSet
from .ServicoViewSet import ServicoViewSet
from .TarefaViewSet import TarefaViewSet
from .RepositorioMiniOSViewSet import RepositorioMiniOSViewSet
from .MiniOSViewSet import MiniOSViewSet
from .FinanceiroKPIsAPIView import FinanceiroKPIsAPIView
from .AnaliseDadosAPIView import AnaliseDadosAPIView
