# Generated by Django 4.2.25 on 2026-07-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_popular_auditoria_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='acao',
            field=models.CharField(choices=[('criacao', 'Criação'), ('atualizacao', 'Atualização'), ('exclusao', 'Exclusão'), ('status', 'Mudança de Status'), ('propagacao_status', 'Propagação de Status'), ('liberacao_faturamento', 'Liberação para Faturamento'), ('faturamento', 'Faturamento'), ('liberacao_cobranca', 'Liberação de Cobrança'), ('cobranca_realizada', 'Cobrança Realizada'), ('contrato', 'Contrato'), ('backfill', 'Backfill')], max_length=40),
        ),
    ]
